# INFO
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@

# SERVER
server:
  port: 8080
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/}

# SPRING
spring:
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always
  main:
    lazy-initialization: true
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/wishlist}
      auto-index-creation: true
  redis:
    client-name: @project.name@
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:}
    ssl: false

# SPRINGDOC
springdoc:
  show-login-endpoint: true
  swagger-ui:
    configUrl: ${SPRINGDOC_SWAGGER_UI_CONFIG_URL:/v3/api-docs/swagger-config}
    disable-swagger-default-url: true
    url: ${SPRINGDOC_SWAGGER_UI_URL:/v3/api-docs}
    operationsSorter: alpha
    tagsSorter: alpha
    defaultModelsExpandDepth: -1

# ACTUATOR
management:
  endpoint:
    health:
      show-details: always
      cache:
        time-to-live: "30s"
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health
