spring:
  config:
    activate:
      on-profile: dev

# ACTUATOR
management:
  endpoint:
    health:
      show-details: always
      cache:
        time-to-live: "30s"
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health
